import { i18n } from '@/i18n'

const t = i18n.global.t

export const evalText = {
  basicData: t('evaluation.generalInformation'),
  environment: t('evaluation.environmentConfiguration'),
  modelData: t('evaluation.modelInformation'),
  input: (item: string) => t('evaluation.input', { item }),
  select: (item: string) => t('evaluation.select', { item }),
  domain: t('evaluation.domain'),
  name: t('evaluation.modelName'),
  description: t('evaluation.description'),
  simpleEval: t('evaluation.evaluationLite'),
  openHfTips: t('evaluation.openHfTips'),
  forMore: t('evaluation.forMore'),
  evalLiteLink: t('evaluation.evalLiteLink'),
  lightweightWarning: t('evaluation.lightweightWarning'),
  huggingFaceModels: t('evaluation.huggingFaceModels'),
  toRegister: t('evaluation.signUp'),
  liteModel: t('evaluation.model'),
  modelType: t('evaluation.modelType'),
  modelTypeTip1: t('evaluation.modelTypeTip1'),
  modelTypeTip2: t('evaluation.modelTypeTip2'),
  precision: t('evaluation.precision'),
  revisionCommit: t('evaluation.revisionCommit'),
  weightsType: t('evaluation.weightsType'),
  baseModel: t('evaluation.baseModel'),
  onlineApiUrl: t('evaluation.apiUrl'),
  onlineKey: t('evaluation.apiKey'),
  onlineModel: t('evaluation.onlineModel'),
  evalDatasets: t('evaluation.datasets'),
  language: t('evaluation.types'),
  system: t('evaluation.evaluationSystem'),
  datasetConfirm: t('evaluation.confirmation'),
  leaderboardDatasets: t('evaluation.listedDatasets'),
  searchDatasets: t('evaluation.searchDatasetName'),
  clickConfirm: t('evaluation.clickConfirm'),
  tasks: t('evaluation.tasks'),
  scene: t('evaluation.deploymentMethod'),
  dimensions: t('evaluation.dimensions'),
  environmentLabel: t('evaluation.environment'),
  url: t('evaluation.evalInterface'),
  interfaceTip: t('evaluation.interfaceTip'),
  interfaceIntroduction: t('evaluation.interfaceIntroduction'),
  mirror: t('evaluation.dockerImage'),
  selectMirror: t('evaluation.chooseImageHere'),
  platformImages: t('evaluation.preInstalledImages'),
  customImages: t('evaluation.customImages'),
  alert: t('evaluation.mirrorAlert'),
  alert2: t('evaluation.mirrorAlert2'),
  mirrorName: t('evaluation.imageName'),
  size: t('common.size'),
  created: t('common.createdAt'),
  mirrorIntro: t('evaluation.imageIntroduction'),
  adaptFrame: t('evaluation.framework'),
  mirrorTags: t('evaluation.tags'),
  applicable: t('evaluation.applicable'),
  dockerfile: t('evaluation.dockerfile'),
  registryUrl: t('images.registryUrl'),
  customEmptyDescription: t('evaluation.noCustomImages'),
  customEmptyInformation: t('evaluation.createApproveImage'),
  customEmptyAction: t('evaluation.createImage'),
  priority: t('evaluation.priority'),
  high: t('common.high'),
  medium: t('common.medium'),
  low: t('common.low'),
  selectCardType: t('evaluation.selectGpu'),
  cardTypeTip: t('evaluation.cardTypeTip'),
  setUpComputedResource: t('evaluation.setUpGpuResource'),
  modelGenKwargs: t('evaluation.modelGenKwargs'),
  paperUrl: t('evaluation.paperUrl'),
  modelUrl: t('evaluation.modelUrl'),
  evalModel: t('evaluation.note'),
  multiSelectTip: t('evaluation.multiSelectTip'),
  modelSelectTip: t('evaluation.modelSelectTip'),
  agreement: t('evaluation.agreement'),
  cancel: t('common.cancel'),
  submit: t('common.submit'),
  edit: t('common.edit'),
  success: t('evaluation.submittedSuccessfully'),
  nlpPackageTip: t('evaluation.nlpPackageTip'),
  orderOfExecution: t('evaluation.order'),
  uploadTokenizer: t('evaluation.upload'),
  uploadTokenizerComment: t('evaluation.uploadTokenizerComment'),
  uploadTokenizerMessage: t('evaluation.uploadTokenizerMessage'),
  pretrainedTokenizerId: t('evaluation.customization'),
  modelNameCheck: t('evaluation.modelNameCheck'),
  modelTypeSwitchMessage: t('evaluation.modelTypeSwitchMessage')
}

export const datasetText = {
  zh: t('evaluation.chinese'),
  en: t('evaluation.english')
}

export const evalBatchText = {
  leaderboadTasks: t('evaluation.benchmarkTask'),
  nonLeaderboardTasks: t('evaluation.nonBenchmarkTask'),
  datasetName: t('evaluation.dataset'),
  datasetDesc: t('common.description')
}

export const multimodalTaskNameMap: Record<string, string> = {
  图问答: t('multimodal.visualQuestionAnswering'),
  文本生成图像: t('multimodal.textToImageGeneration'),
  '图像-文本匹配': t('multimodal.imageTextMatching'),
  文生视频: t('multimodal.textToVideo'),
  视频理解: t('multimodal.videoUnderstanding'),
  视觉定位: t('multimodal.visualGrounding'),
  指代表达: t('multimodal.visualGrounding'),
  文本检索视频: 'Text to video retrieval',
  视频文本检索: 'Video retrival',
  视频问答: t('multimodal.videoQuestionAnswering'),
  色彩理解: 'Color Bench',
  '文本-图像匹配': t('multimodal.textImageMatching')
}

export const TOKENIZERS = [
  'gpt2',
  'BAAI/AquilaChat-7B',
  'BAAI/Aquila-7B',
  'tiiuae/falcon-7b',
  'THUDM/chatglm2-6b',
  'TsinghuaKEG/ice',
  'internlm/internlm-7b',
  'baichuan-inc/Baichuan-13B-Chat',
  'ziqingyang/chinese-llama-2-7b',
  'yulan-team/YuLan-Chat-2-13b',
  'Qwen/Qwen-1_8B',
  'Qwen2.5-7B-Instruct'
]
