server {
    listen  8080;

    keepalive_timeout 300;
    client_max_body_size 11m;

    charset utf-8;

    add_header "X-UA-Compatible" "IE=Edge";
    location / {
        auth_basic "Restricted Files";
        auth_basic_user_file /etc/nginx/.htpasswd;
        root /share/project/eval_results;
    }
}