# Generated by Django 4.2.30 on 2026-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.BigIntegerField()),
                ('dataset_id', models.BigIntegerField()),
                ('disturbance', models.CharField(default='', max_length=200)),
                ('scenario_entry_point', models.CharField(default='', max_length=40)),
                ('result', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('started_at', models.BigIntegerField(null=True)),
                ('stopped_at', models.BigIntegerField(null=True)),
                ('total_instances', models.BigIntegerField(null=True)),
                ('avg_elapsed', models.BigIntegerField(null=True)),
                ('max_elapsed', models.BigIntegerField(null=True)),
            ],
            options={
                'index_together': {('batch_id', 'dataset_id', 'disturbance')},
            },
        ),
        migrations.CreateModel(
            name='DAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.BigIntegerField(default=0)),
                ('batch_id', models.BigIntegerField()),
                ('scenario_entry_point', models.CharField(default='', max_length=40)),
                ('dataset_id', models.BigIntegerField(default=0)),
                ('run_entry', models.CharField(max_length=512)),
                ('disturbance', models.CharField(default='', max_length=200)),
                ('disturbance_opts', models.JSONField(default=dict)),
                ('celery_task_id', models.CharField(db_index=True, max_length=40)),
                ('result', models.JSONField()),
                ('status', models.CharField(choices=[('M', 'MODIFIED'), ('P', 'Pending'), ('PPR', 'Platform Preparing'), ('PPE', 'Platform Pending'), ('PST', 'Platform Starting'), ('PSC', 'Platform Scheduling'), ('R', 'Running'), ('DI', 'Done Inference'), ('HE', 'Human Evaluating'), ('S', 'Success'), ('F', 'Failure'), ('C', 'Cancel')], max_length=3)),
                ('delayed_uuid', models.UUIDField(editable=False, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('started_at', models.BigIntegerField(null=True)),
                ('stopped_at', models.BigIntegerField(null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'unique_together': {('batch_id', 'run_entry', 'disturbance')},
                'index_together': {('batch_id', 'scenario_entry_point', 'dataset_id')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.BigIntegerField(db_index=True)),
                ('sequence', models.BigIntegerField(default=0)),
                ('try_sequence', models.IntegerField(default=0)),
                ('user_id', models.BigIntegerField()),
                ('celery_task_id', models.CharField(db_index=True, max_length=40)),
                ('joint_job_id', models.CharField(default='', max_length=40)),
                ('resource', models.JSONField()),
                ('priority', models.CharField(default='high', max_length=20)),
                ('submitted', models.BooleanField(default=False)),
                ('results', models.JSONField(default=list)),
                ('dry_run', models.BooleanField(default=False)),
                ('model_storage_url', models.CharField(default='', max_length=512)),
                ('model_id', models.BigIntegerField(default=0)),
                ('model_revision', models.BigIntegerField(default=0)),
                ('dags_ready', models.BooleanField(default=True)),
                ('dags_delayed_tasks', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('M', 'MODIFIED'), ('P', 'Pending'), ('PPR', 'Platform Preparing'), ('PPE', 'Platform Pending'), ('PST', 'Platform Starting'), ('PSC', 'Platform Scheduling'), ('R', 'Running'), ('DI', 'Done Inference'), ('HE', 'Human Evaluating'), ('S', 'Success'), ('F', 'Failure'), ('C', 'Cancel')], default='F', max_length=3)),
                ('failure_kind', models.CharField(choices=[('SYS', 'System'), ('MOD', 'Model')], max_length=3, null=True)),
                ('failure_details', models.TextField(null=True)),
                ('include_robustness', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('datasets_config', models.JSONField(default=dict)),
                ('nlp_trending', models.JSONField(default=dict)),
            ],
            options={
                'index_together': {('user_id', 'created_at')},
            },
        ),
    ]
