"""
Django settings for paneval project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

WEBSITE_URL = "http://localhost:8080"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yx5gas0^+xqfquwgu3s41(#fts7l_31xtki=x&+gt5$15!0ad%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party.
    "django_celery_results",
    "corsheaders",
    "rest_framework",

    # Apps.
    "paneval.apps.user",
    "paneval.apps.evaluation",
    "paneval.apps.cem",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'djangorestframework_camel_case.middleware.CamelCaseMiddleWare',
]

ROOT_URLCONF = "paneval.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "paneval.wsgi.application"
ASGI_APPLICATION = "paneval.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": "db",
        "NAME": "paneval",
        "USER": "paneval",
        "PASSWORD": "insecure-K06rgM43dJg0F9O0-insecure",
        "OPTIONS": {
            "charset": "utf8mb4"  # This is the relevant line
        },
    },
}


REDIS_BASE_URL = "redis://redis:6379"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_BASE_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    'paneval.apps.user.auth.UsernamePasswordBackend',
    'paneval.apps.user.auth.SMSCodeBackend',
]

AUTH_USER_MODEL = "user.User"

# OpenID Connect. Leave OIDC_ENABLED unset to enable automatically when issuer,
# client ID, and client secret are all configured.
OIDC_ENABLED = os.environ.get("PANEVAL_OIDC_ENABLED", "")
OIDC_ISSUER_URL = os.environ.get("PANEVAL_OIDC_ISSUER_URL", "")
OIDC_CLIENT_ID = os.environ.get("PANEVAL_OIDC_CLIENT_ID", "")
OIDC_CLIENT_SECRET = os.environ.get("PANEVAL_OIDC_CLIENT_SECRET", "")
OIDC_SCOPES = os.environ.get("PANEVAL_OIDC_SCOPES", "openid email profile")
OIDC_REDIRECT_PATH = os.environ.get(
    "PANEVAL_OIDC_REDIRECT_PATH",
    "/api/users/sso",
)
OIDC_REDIRECT_URI = os.environ.get("PANEVAL_OIDC_REDIRECT_URI", "")
OIDC_SUCCESS_REDIRECT = os.environ.get("PANEVAL_OIDC_SUCCESS_REDIRECT", "")
OIDC_HTTP_TIMEOUT = os.environ.get("PANEVAL_OIDC_HTTP_TIMEOUT", "5")


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'paneval/locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CSRF_TRUSTED_ORIGINS = [
]

# Third-Party
CORS_ALLOWED_ORIGINS = [
]

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-request-id",
)

CORS_ALLOW_CREDENTIALS = True
# Django Rest Framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ],

    'DEFAULT_PARSER_CLASSES': (
        # If you use MultiPartFormParser or FormParser, we also have a camel case version
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        # Any other parsers
    ),
    'JSON_UNDERSCOREIZE': {
        'no_underscore_before_number': True,
        'ignore_fields': ('raw_details',),
    },
    'DEFAULT_PAGINATION_CLASS': 'paneval.util.PanevalPagination',  # noqa
    'PAGE_SIZE': 10,

}

# 需同步到 Executor 的评测数据集
STORAGE_DATASETS = {
    # 需同步到九鼎平台的 NLP 评测数据集
    'N': {
        'conda': {
            'STORAGE_KEY': 'mnt/envs/conda/2024-03-14',
            'DOWNLOAD_ID': '605855df-7b89-43e7-a896-64f13ae8fc7c',
        },
        'lmeval': {
            'STORAGE_KEY': 'mnt/lm_eval/2025-02-19',
            'DOWNLOAD_ID': '6c12531f-c304-496b-83c4-45ba63a1637a',
        },
    },
    'M': {
        'conda': {
            'STORAGE_KEY': 'mnt/evalmm/conda/20260624',
            'DOWNLOAD_ID': 'a33068a6-5c1e-4083-97a8-7313d1ba5d29',
        },
        'datasets': {
            'STORAGE_KEY': 'mnt/evalmm/datasets/20260624',
            'DOWNLOAD_ID': 'edcdc508-165f-49ea-8e12-35546b6def0f',
        },
    }
}

# Celery
# Celery Configuration Options
CELERY_BROKER_URL = f'{REDIS_BASE_URL}/2'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# We only use Celery for trusted clients, so pickle is acceptable.
# More details to see:
# https://docs.celeryq.dev/en/stable/userguide/security.html#serializers
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['pickle']
CELERY_RESULT_ACCEPT_CONTENT = ['json']

# Debug in Celery
# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES = True

# Result
CELERY_IGNORE_RESULT = False
CELERY_RESULT_BACKEND = f'{REDIS_BASE_URL}/3'  # Chord requires Redis.
CELERY_CACHE_BACKEND = 'django-cache'


SSH_EXECUTOR = {
    'model_root': '/share/project',
    'result': {
        'job_root': '/share/project/eval_results',
        'serving_host': 'http://executor:8080/',
        'prefix': 'test-',
        'authentication': {
            'username': os.environ.get('PANEVAL_EXECUTOR_HTTP_USER'),
            'password': os.environ.get('PANEVAL_EXECUTOR_HTTP_PASSWD'),
        },
    },
    'conf': {
        'online_ssh_host': 'root@executor',
        'online_ssh_port': 3022,
    },
}

# 分块上传的大小
CHUNK_SIZE_KB = 10 * 1024  # 10M

# Error reporting
ADMINS = [
    ("Hui", "wh_linux@126.com"),
]


TOKENIZER_BASE_PATH = '/tmp/tokenizers'

FILESYSTEM_OBJECT_STORAGE_PATH = '/share/project/objects'

try:
    from local_settings import *  # noqa
except ImportError:
    pass
