# Generated by Django 4.2.30 on 2026-06-09 11:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('task', models.CharField(choices=[('EA', 'API Evaluate'), ('EM', 'Model Evaluate'), ('TM', 'Model Train')], max_length=2)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'index_together': {('user_id', 'deleted_at')},
            },
        ),
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('social_platform', models.CharField(choices=[('WX', 'WeChat'), ('EM', 'Email'), ('UN', 'Username'), ('HF', 'HuggingFace')], max_length=2)),
                ('social_open_id', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=64)),
                ('password_salt', models.CharField(default='', max_length=16)),
                ('extras', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('user_id', 'social_platform'), ('social_platform', 'social_open_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country_code', models.CharField(default='+86', max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=40)),
                ('organization', models.CharField(default='', max_length=128)),
                ('organization_en', models.CharField(default='', max_length=128)),
                ('team_id', models.BigIntegerField(default=0)),
                ('feishu_id', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('I', 'INCOMPLETE'), ('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='I', max_length=1)),
                ('user_center', models.JSONField(default=dict)),
                ('is_private_model', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('eva_count', models.IntegerField(default=5)),
                ('eva_used', models.IntegerField(default=0)),
                ('mark_count', models.IntegerField(default=2)),
                ('mark_used', models.IntegerField(default=0)),
                ('is_researcher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('country_code', 'phone')},
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
