# Generated by Django 4.2.30 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add OpenID Connect as a social account platform."""

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialaccount',
            name='social_platform',
            field=models.CharField(
                choices=[
                    ('WX', 'WeChat'),
                    ('EM', 'Email'),
                    ('UN', 'Username'),
                    ('HF', 'HuggingFace'),
                    ('OC', 'OpenID Connect'),
                ],
                max_length=2,
            ),
        ),
    ]
